# Usage: Use CI/CD Image locally

version: '3.5'

services:
  cicd:
    image: ejplatform/ej-cicd:latest
    links:
      - docker
    environment:
      DOCKER_HOST: tcp://docker:2375
    volumes:
      - ../../:/app
    working_dir: /app

  docker:
    image: docker:dind
    privileged: true
