image: ejplatform/ej-cicd:latest
services:
  - docker:dind

stages:
  - push base
  - test
  - push image
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# Stage: push base
push all base images:
  stage: push base
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - docker-compose -f ./docker/base/base.build.yml build
    - docker-compose -f ./docker/base/test.build.yml build
    - docker-compose -f ./docker/base/production.build.yml build
    - docker-compose -f ./docker/base/base.build.yml push
    - docker-compose -f ./docker/base/test.build.yml push
    - docker-compose -f ./docker/base/production.build.yml push
  only:
    - /base/
  tags:
    - docker

push test base image:
  stage: push base
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - docker-compose -f ./docker/base/test.build.yml build
    - docker-compose -f ./docker/base/test.build.yml push
  only:
    - /base_test/
  tags:
    - docker

push production base image:
  stage: push base
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - docker-compose -f ./docker/base/production.build.yml build
    - docker-compose -f ./docker/base/production.build.yml push
  only:
    - /base_production/
  tags:
    - docker

# Stage: test
test:
  stage: test
  script:
    - docker-compose -f ./docker/local/test.yml run --rm django
  tags:
    - docker

# Stage: push image
push develop images:
  stage: push image
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - docker-compose -f ./docker/production/staging.build.yml build
    - docker-compose -f ./docker/production/staging.build.yml push
  only:
    - /develop/
  tags:
    - docker

push production images:
  stage: push image
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - docker-compose -f ./docker/production/latest.build.yml build
    - docker-compose -f ./docker/production/latest.build.yml push
  only:
    - /master/
  tags:
    - docker

# Stage: deploy
deploy to development:
  stage: deploy
  environment: develop
  script:
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service backend --no-finish-upgrade --sidekicks
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service flower --no-finish-upgrade
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service worker --no-finish-upgrade
  only:
    - /develop/
  tags:
    - docker

deploy to production:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  environment: production
  script:
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service backend --no-finish-upgrade --sidekicks
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service flower --no-finish-upgrade
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service worker --no-finish-upgrade
  only:
    - /master/
  tags:
    - docker
