image: ejplatform/ej-cicd:latest
services:
  - docker:dind

stages:
  - test
  - push
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive
  DJANGO_MASTER_IMAGE: "ejplatform/ej-server:master"
  DJANGO_LATEST_IMAGE: "ejplatform/ej-server:latest"
  BACKEND_MASTER_IMAGE: "ejplatform/ej-nginx:master"
  BACKEND_LATEST_IMAGE: "ejplatform/ej-nginx:latest"


#
# Testing
#

test:
  stage: test
  script:
    - docker pull $DJANGO_MASTER_IMAGE || true
    - docker build --cache-from $DJANGO_MASTER_IMAGE -t $DJANGO_MASTER_IMAGE -f ./docker/production/django/Dockerfile .
    - docker-compose -f ./docker/develop/test.yml run
    - docker save $DJANGO_MASTER_IMAGE -o image.tar
  tags:
    - docker
  cache:
    key: image
    paths:
      - image.tar

#
# Pushing images to registry
#

push master images:
  stage: push
  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
  script:
    - docker load -i image.tar
    - docker build -t $BACKEND_MASTER_IMAGE -f ./docker/production/nginx/master.Dockerfile .
    - docker push $BACKEND_MASTER_IMAGE
    - docker push $DJANGO_MASTER_IMAGE
  only:
    - master
  tags:
    - docker
  cache:
    key: image
    paths:
      - image.tar
    policy: pull

push latest images:
  stage: push
  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
  script:
    - docker load -i image.tar
    - docker build -t $BACKEND_LATEST_IMAGE -f ./docker/production/nginx/latest.Dockerfile .
    - docker push $BACKEND_LATEST_IMAGE
    - docker push $DJANGO_LATEST_IMAGE
  only:
    - tags
  tags:
    - docker
  cache:
    key: image
    paths:
      - image.tar
    policy: pull

#
# Rancher service upgrade
#

deploy master images:
  stage: deploy
  environment: develop
  script:
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service backend --no-finish-upgrade --sidekicks
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service flower --no-finish-upgrade
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service worker --no-finish-upgrade
  only:
    - master
  tags:
    - docker

deploy latest images:
  stage: deploy
  environment: production
  script:
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service backend --no-finish-upgrade --sidekicks
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service flower --no-finish-upgrade
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service worker --no-finish-upgrade
  only:
    - tags
  tags:
    - docker
