image: docker:18.01.0-ce-git
services:
  - docker:dind
stages:
  - test
  - push image
  - deploy

# Stage: test
test:
  stage: test
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - docker-compose -f ./test.yml run django
  tags:
    - docker

# Stage: push image
push develop image:
  stage: push image
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - docker build -f ./compose/production/Dockerfile --target django -t $DOCKER_HUB_ORGANIZATION/ej-server:develop .
    - docker build -f ./compose/production/Dockerfile --target nginx -t $DOCKER_HUB_ORGANIZATION/ej-nginx:develop .
    - docker push $DOCKER_HUB_ORGANIZATION/ej-server:develop
    - docker push $DOCKER_HUB_ORGANIZATION/ej-nginx:develop
  only:
    - /develop/
  tags:
    - docker

push production images:
  stage: push image
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - docker build -f ./compose/production/Dockerfile --target django -t $DOCKER_HUB_ORGANIZATION/ej-server:latest .
    - docker build -f ./compose/production/Dockerfile --target nginx -t $DOCKER_HUB_ORGANIZATION/ej-nginx:latest .
    - docker push $DOCKER_HUB_ORGANIZATION/ej-server:latest
    - docker push $DOCKER_HUB_ORGANIZATION/ej-nginx:latest
  only:
    - /master/
  tags:
    - docker

push release images:
  stage: push image
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - docker build -f ./compose/production/Dockerfile --target django -t $DOCKER_HUB_ORGANIZATION/ej-server:$CI_COMMIT_TAG .
    - docker build -f ./compose/production/Dockerfile --target nginx -t $DOCKER_HUB_ORGANIZATION/ej-nginx:$CI_COMMIT_TAG .
    - docker push $DOCKER_HUB_ORGANIZATION/ej-server:$CI_COMMIT_TAG
    - docker push $DOCKER_HUB_ORGANIZATION/ej-nginx:$CI_COMMIT_TAG
  only:
    - tags
  tags:
    - docker

# Stage: deploy
deploy to development:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  environment: develop
  script:
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service backend --no-finish-upgrade --sidekicks
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service flower --no-finish-upgrade
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service worker --no-finish-upgrade
  only:
    - /develop/
  tags:
    - docker

deploy to production:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  environment: production
  script:
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service backend --no-finish-upgrade --sidekicks
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service flower --no-finish-upgrade
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service worker --no-finish-upgrade
  only:
    - /master/
  tags:
    - docker
