services:
  - docker:dind

stages:
  - build
  - test
  - release

variables:
  DOCKER_DRIVER: overlay2


# Reusable configurations
.container: &container
  image: docker
  before_script:
    - &install apk add python3 && python3 -m pip install invoke~=0.23
    - &login docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
  tags:
    - docker

.runner: &runner
  << : *container
  before_script:
    - *install
    - &pull inv -e docker-pull -t $CI_COMMIT_REF_SLUG --theme=$THEMES

.publisher: &publisher
  << : *container
  before_script:
    - *install
    - *login
    - docker pull cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service backend --sidekicks --no-finish-upgrade


# BUILD: build and publish images using the CI_COMMIT_REF_SLUG.
# Those images will not be published under :latest and :tag automatically.
# Only master commits publish images under the :latest tags on dockerhub
# and commits with tags create tagged images.
build:
  << : *container
  script:
    - *login
    - inv -e docker-build -t $CI_COMMIT_REF_SLUG --theme=$THEMES
    - inv -e docker-push  -t $CI_COMMIT_REF_SLUG --theme=$THEMES


# TEST: test in different environments by changing the database or running a
# linter
test:sqlite3:
  << : *runner
  stage: test
  script:
    - inv -e docker-run --cmd test

test:postgres:
  << : *runner
  stage: test
  script:
    - inv docker-run -e dev --cmd test

test:lint:
  << : *runner
  stage: test
  script:
    - inv docker-run --cmd lint


# PUSH: commits on master
release:master:
  << : *publisher
  stage: push
  script:
    - inv docker-push --from $CI_COMMIT_REF_SLUG
    - inv rancher-push
  only:
    - master

release:tag:
  << : *publisher
  stage: push
  script:
    - inv docker-push --from $CI_COMMIT_REF_SLUG -t $CI_COMMIT_TAG
    - inv rancher-push -t $CI_COMMIT_TAG
  only:
    - tags


#push:latest:django:cpa:
#  << : *buildercpa
#  stage: push
#  script:
#    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
#    - docker tag $CPA_DJANGO_MASTER_IMAGE $CPA_DJANGO_LATEST_IMAGE
#    - docker push $CPA_DJANGO_LATEST_IMAGE
#  only:
#    - tags
#
#
##
#
#deploy:master:generic:
#  << : *deployer
#  stage: deploy
#  environment: develop
#  only:
#    - master
#
#deploy:latest:generic:
#  << : *deployer
#  stage: deploy
#  environment: production
#  only:
#    - tags
#
#deploy:master:cpa:
#  << : *deployer
#  stage: deploy
#  environment: develop_cpa
#  only:
#    - master
#
#deploy:latest:cpa:
#  << : *deployer
#  stage: deploy
#  environment: production_cpa
#  only:
#    - tags
