image: ejplatform/ej-cicd:latest
services:
  - docker:dind

stages:
  - test
  - push
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive
  MASTER_IMAGE: "ejplatform/ej-server:master"
  DEVELOP_IMAGE: "ejplatform/ej-server:develop"
  LATEST_IMAGE: "ejplatform/ej-server:latest"

before_script:
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS

#
# Testing
#

test:
  stage: test
  script:
    - docker pull $MASTER_IMAGE || true
    - docker-compose -f ./docker/production/django/build.yml build
    - docker tag $MASTER_IMAGE $DEVELOP_IMAGE
    - docker-compose -f ./docker/develop/test.yml build
    - docker-compose -f ./docker/develop/test.yml run --rm django
    - docker save $MASTER_IMAGE image.tar
  tags:
    - docker
  cache:
    key: image
    paths:
      - image.tar

#
# Pushing images to registry
#

push master images:
  stage: push
  script:
    - docker load -i image.tar
    - docker-compose -f ./docker/production/master.build.yml build
    - docker-compose -f ./docker/production/master.build.yml push
  only:
    - master
  tags:
    - docker
  cache:
    key: image
    paths:
      - image.tar
    policy: pull

push latest images:
  stage: push
  script:
    - docker load -i image.tar
    - docker tag $MASTER_IMAGE $LATEST_IMAGE
    - docker-compose -f ./docker/production/latest.build.yml build
    - docker-compose -f ./docker/production/latest.build.yml push
  only:
    - tags
  tags:
    - docker
  cache:
    key: image
    paths:
      - image.tar
    policy: pull

#
# Rancher service upgrade
#

deploy master images:
  stage: deploy
  environment: develop
  script:
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service backend --no-finish-upgrade --sidekicks
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service flower --no-finish-upgrade
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service worker --no-finish-upgrade
  only:
    - master
  tags:
    - docker

deploy latest images:
  stage: deploy
  environment: production
  script:
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service backend --no-finish-upgrade --sidekicks
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service flower --no-finish-upgrade
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service worker --no-finish-upgrade
  only:
    - tags
  tags:
    - docker
