version: '2'

volumes:
  db_data: {}

services:

  redis:
    image: redis:2.8.19
    hostname: redis

  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.0
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=pushtogether
      - POSTGRES_USER=pushtogether
      - POSTGRES_PASSWORD=pushtogether
      - USE_DOCKER=yes
      - COURIER_DEFAULT_PROVIDER=onesignal
      - COURIER_ONESIGNAL_APP_ID=660977f0-30ad-4f69-a9a4-2873b8f5de7e
      - COURIER_ONESIGNAL_USER_ID=NTlmYjI5NDktYzA1Zi00ODk4LTllZGQtYWEzY2Q4ZjA3YzM5
    links:
      - postgres
      - rabbit
      - redis
    ports:
      - "8000:8000"
    command: /runserver.sh

  postgres:
    image: postgres:9.6
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pushtogether
      - POSTGRES_USER=pushtogether
      - POSTGRES_PASSWORD=pushtogether

  worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: ./run_celery.sh
    volumes:
      - .:/app
    links:
      - postgres
      - rabbit
      - redis
    depends_on:
      - rabbit
