version: '2'

volumes:
  db_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=pushtogether
      - USE_DOCKER=yes
      - COURIER_DEFAULT_PROVIDER=onesignal
      - COURIER_ONESIGNAL_APP_ID=660977f0-30ad-4f69-a9a4-2873b8f5de7e
      - COURIER_ONESIGNAL_USER_ID=NTlmYjI5NDktYzA1Zi00ODk4LTllZGQtYWEzY2Q4ZjA3YzM5
    ports:
      - "8000:8000"
    command: /start.sh

  postgres:
    image: postgres:9.6
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pushtogether


