version: '2'

volumes:
  db_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=pushtogether
      - POSTGRES_PASSWORD=pushtogether
      - POSTGRES_DB=pushtogether
      - USE_DOCKER=yes
    ports:
      - "8000:8000"
    command: /start.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - USER_PG=pushtogether
      - PASSWORD_PG=pushtogether
      - DB_PG=pushtogether
