version: '2'

volumes:
  db_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - /app/staticfiles
    command: /gunicorn.sh

  postgres:
    image: postgres:9.6
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    volumes_from:
      - django
    depends_on:
      - django
    ports:
      - "80:80"
