# Generic production docker-compose file
# Create the env files before using this

version: '3.5'

volumes:
  postgres_data: {}
  user_media: {}
  user_static: {}

services:
  django: &django
    image: ejplatform/ej-server:latest
    env_file:
      - ./compose/production/django.env
      - ./compose/production/postgres.env
    volumes:
      - user_media:/app/staticfiles/media

  backend:
    image: ejplatform/ej-server-nginx:latest
    volumes:
      - user_media:/usr/share/nginx/html/media

  lb:
    image: rancher/lb-service-haproxy:v0.6.2
    expose:
      - 80:80/tcp

  redis:
    image: redis:3

  rabbit:
    image: rabbitmq:3.6.14-management
    env_file:
      - ./compose/production/rabbit.env

  flower:
    << : *django
    command: ./compose/production/flower/start_flower.sh

  worker:
    << : *django
    command: ./compose/production/worker/run_celery.sh

  postgres:
    image: postgres:9.6
    env_file:
      - ./compose/production/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    image: ejplatform/ej-front:latest
    volumes:
      - user_static:/usr/share/nginx/html/static
      - user_media:/usr/share/nginx/html/media

