version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - /app/staticfiles
    command: /gunicorn.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    volumes_from:
      - django
    depends_on:
      - django
    ports:
      - "80:80"
