version: '2'

services:
  postgres:
    env_file:
      - ./compose/dev/postgres.env
    image: postgres:9.6

  django:
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    command: /test.sh
    depends_on:
      - postgres
    env_file:
      - ./compose/dev/django.env
      - ./compose/dev/postgres.env
