# Test docker-compose file
# Used in CI/CD tools

version: '3.5'

services:
  postgres:
    image: postgres:9.6
    env_file:
      - ./compose/dev/postgres.env

  django:
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    command: /test.sh
    depends_on:
      - postgres
    env_file:
      - ./compose/dev/django.env
      - ./compose/dev/postgres.env
