# This docker-compose file is not runnable
# Usage: Build & Push

version: '3.5'

services:
  django:
    image: ej-server:local
    build:
      context: ../../
      dockerfile: ./docker/local/django/Dockerfile
