version: '3.5'


services:
  nginx:
    image: nginx:alpine
    restart: always
    build:
      context: ../
      dockerfile: ./docker/Dockerfile-nginx
    volumes:
      - media_files:/usr/share/nginx/html/media
      - static_files:/usr/share/nginx/html/static
    ports:
      - 80:80
    links:
      - web:django

  web:
    image: ejplatform/web:latest
    restart: always
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "5000:8000"
    links:
      - postgres:postgres
      - redis:redis
    env_file:
      - ./env/django.env
      - ./env/postgres.env
      - ./env/deploy.env
    environment:
      - DJANGO_ENVIRONMENT=production
      - DJANGO_DEBUG
      - DJANGO_ALLOWED_HOSTS=localhost
    volumes:
      - media_files:/app/local/media/
      - static_files:/app/local/static/
    working_dir: /app
    command: db -m gunicorn

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - ./env/deploy.env
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always


volumes:
  db_data:
  media_files:
  static_files:
