version: '3.5'


services:
  rocketchat:
    image: rocketchat/rocket.chat:${ROCKETCHAT_VERSION:-latest}
    environment:
      MONGO_URL: mongodb://mongo:27017/rocketchat
      PORT: '3000'
      ROOT_URL: http://${HOSTNAME:-localhost}:3000
    links:
      - mongo:mongo
    ports:
      - 3000:3000

  mongo:
    image: mongo
    volumes:
      - db_rocketchat:/data/db
    command:
      - mongod
      - --smallfiles
      - --oplogSize
      - '128'

volumes:
  db_rocketchat:
