version: '3.5'


services:
  nginx:
    image: ejplatform/nginx:latest
    volumes:
      - media_files:/usr/share/nginx/html/media
      - static_files:/usr/share/nginx/html/static
    ports:
      - 80:80
    depends_on:
      - web
    links:
      - web

  web:
    image: ejplatform/web:latest
    restart: always
    links:
      - postgres
      - redis
    env_file:
      - ./env/django.env
      - ./env/postgres.env
      - ./env/deploy.env
    volumes:
      - media_files:/app/local/media/
      - static_files:/app/local/static/
      - nginx_conf:/etc/nginx/conf.d/
    command: clean db-assets sass collect db -m gunicorn

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - ./env/deploy.env
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always


volumes:
  db_data:
  media_files:
  static_files:
  nginx_conf:
