version: '3.5'


volumes:
  db_data:


services:
  web: &django
    restart: always
    image: ejplatform/dev:latest
    build:
      context: ../../
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
      - redis:redis
    env_file:
      - ./env/django.env
      - ./env/postgres.env
    environment:
      - DJANGO_ENVIRONMENT=local
      - EJ_TITLE=1
    volumes:
      - ../../:/app/
    working_dir: /app
    command: run


  postgres:
    restart: always
    image: postgres:9.6
    env_file:
      - ./env/postgres.env
    volumes:
      - db_data:/var/lib/postgresql/data


  redis:
    restart: always
    image: redis:3
