# This docker-compose file is not designed to run
# Usage: Build & Push

version: '3.5'

services:
  django:
    image: ejplatform/ej-server:master
    build:
      context: ../../
      dockerfile: ./docker/production/django/Dockerfile
      cache_from:
        - ejplatform/ej-server:master

  backend:
    image: ejplatform/ej-nginx:master
    depends_on:
      - django
    build:
      context: ../../
      dockerfile: ./docker/production/nginx/master.Dockerfile
