# This docker-compose file is not designed to run
# Usage: Build & Push

version: '3.5'

services:
  django:
    image: ejplatform/ej-server:develop
    build:
      context: ../../
      dockerfile: ./docker/production/django/Dockerfile

  backend:
    image: ejplatform/ej-nginx:develop
    depends_on:
      - django
    build:
      context: ../../
      dockerfile: ./docker/production/nginx/staging.Dockerfile
