version: '3.5'


volumes:
  db_data:


services:
  web: &django
    restart: always
    image: ejplatform/web:latest
    build:
      context: ../../
      dockerfile: ./docker/Dockerfile
    ports:
      - "5000:8000"
    links:
      - postgres:postgres
      - redis:redis
    env_file:
      - ../env/django.env
      - ../env/postgres.env
      - ../env/deploy.env
    environment:
      #- DJANGO_ENVIRONMENT=production
      - EJ_TITLE=1
    volumes:
      - ../../local/docker/static/media/:/app/local/media/
    working_dir: /app
    command: db -m run-deploy


  nginx:
    restart: always
    image: ejplatform/ej-nginx:latest
    volumes:
      - ../../local/docker/media/:/usr/share/nginx/html/media
    ports:
      - 80:80
    links:
      - web:django


  postgres:
    restart: always
    image: postgres:9.6
    env_file:
      - ../env/deploy.env
    volumes:
      - db_data:/var/lib/postgresql/data


  redis:
    restart: always
    image: redis:3


#  rabbit:
#    image: rabbitmq:3.6.14-management
#    env_file:
#      - ./env/rabbit.env
#    ports:
#      - 5672:5672  # Debugging
#      - 15672:15672  # RabbitMQ Manager

