# Local docker-compose file
version: '3.5'

networks:
  ej:
    name: ej

volumes:
  db_data: {}

services:
  django: &django
    image: ejplatform/ej-server:develop
    build:
      context: ../../
      dockerfile: ./docker/develop/django/Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./env/django.env
      - ./env/postgres.env
    links:
      - postgres
      - rabbit
      - redis
    networks:
      - ej
    ports:
      - 8000:8000
    volumes:
      - ../../:/app
    working_dir: /app

  redis:
    image: redis:3.2
    networks:
      - ej

  rabbit:
    image: rabbitmq:3.6.14-management
    env_file:
      - ./env/rabbit.env
    networks:
      - ej
    ports:
      - 5672:5672  # Debugging
      - 15672:15672  # RabbitMQ Manager

  postgres:
    image: postgres:9.6
    env_file:
      - ./env/postgres.env
    networks:
      - ej
    volumes:
      - db_data:/var/lib/postgresql/data
